/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#0053db",
        "on-tertiary-fixed-variant": "#454749",
        "surface-container-high": "#e1e8fd",
        "on-secondary-fixed-variant": "#404754",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary": "#ffffff",
        "on-background": "#141b2b",
        "on-surface-variant": "#434655",
        "inverse-surface": "#293040",
        "surface-container-highest": "#dce2f7",
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#dce2f3",
        "tertiary-fixed-dim": "#c6c6c8",
        "tertiary": "#535557",
        "tertiary-fixed": "#e2e2e4",
        "secondary-container": "#dce2f3",
        "primary-fixed-dim": "#b4c5ff",
        "secondary": "#585f6c",
        "background": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "primary": "#004ac6",
        "primary-container": "#2563eb",
        "outline": "#737686",
        "outline-variant": "#e5e7eb",
        "surface-dim": "#d3daef",
        "on-error": "#ffffff",
        "on-primary-container": "#eeefff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#151c27",
        "surface-bright": "#f9f9ff",
        "secondary-fixed-dim": "#c0c7d6",
        "on-secondary": "#ffffff",
        "surface": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "on-surface": "#141b2b",
        "on-secondary-container": "#5e6572",
        "surface-container-low": "#f1f3ff",
        "surface-container": "#e9edff",
        "on-tertiary-fixed": "#1a1c1d",
        "inverse-on-surface": "#edf0ff",
        "error": "#ba1a1a",
        "on-primary-fixed": "#00174b",
        "surface-variant": "#f5f5f7",
        "on-tertiary-container": "#f0f0f2",
        "tertiary-container": "#6c6d6f",
        "inverse-primary": "#b4c5ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "title-lg": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
